"""add language to posts

Revision ID: 119e8b16cb6d
Revises: ebf2d7323ea1
Create Date: 2022-01-30 11:19:22.548246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119e8b16cb6d'
down_revision = 'ebf2d7323ea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
